// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDY3xtlSLz9a2YMe58I9pH00cjFGKsk3ls',
//     appId: '1:935376476313:web:e01ebd9e7411582c0c8008',
//     messagingSenderId: '935376476313',
//     projectId: 'dynamiclink-55a04',
//     authDomain: 'dynamiclink-55a04.firebaseapp.com',
//     storageBucket: 'dynamiclink-55a04.appspot.com',
//     measurementId: 'G-7L2DYBSY57',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAw1ldNKD4Gw7ORv_4m0_aPIoRGS1I4mx8',
//     appId: '1:935376476313:android:0ae7ecee79cf8dfa0c8008',
//     messagingSenderId: '935376476313',
//     projectId: 'dynamiclink-55a04',
//     storageBucket: 'dynamiclink-55a04.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDJvjTBu_M8oW4wFIx-2WMk0jF_Y75l60o',
//     appId: '1:935376476313:ios:09ee2a7d98cae3ad0c8008',
//     messagingSenderId: '935376476313',
//     projectId: 'dynamiclink-55a04',
//     storageBucket: 'dynamiclink-55a04.appspot.com',
//     iosBundleId: 'com.example.dynamiclink',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyDJvjTBu_M8oW4wFIx-2WMk0jF_Y75l60o',
//     appId: '1:935376476313:ios:09ee2a7d98cae3ad0c8008',
//     messagingSenderId: '935376476313',
//     projectId: 'dynamiclink-55a04',
//     storageBucket: 'dynamiclink-55a04.appspot.com',
//     iosBundleId: 'com.example.dynamiclink',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyDY3xtlSLz9a2YMe58I9pH00cjFGKsk3ls',
//     appId: '1:935376476313:web:021fa26ea0a1785e0c8008',
//     messagingSenderId: '935376476313',
//     projectId: 'dynamiclink-55a04',
//     authDomain: 'dynamiclink-55a04.firebaseapp.com',
//     storageBucket: 'dynamiclink-55a04.appspot.com',
//     measurementId: 'G-XXF0QE807H',
//   );
// }
